"""add position field to chat model

Revision ID: 56b7545a27dd
Revises: 16c3a2ff1f7e
Create Date: 2026-02-06 02:10:06.650039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "56b7545a27dd"
down_revision: Union[str, Sequence[str], None] = "16c3a2ff1f7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats",
        sa.Column(
            "position", sa.Integer(), autoincrement=True, nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "position")
    # ### end Alembic commands ###
