"""change in chat and user model

Revision ID: bd45129b23a3
Revises: b57648f88fc0
Create Date: 2026-02-04 22:42:22.348292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bd45129b23a3"
down_revision: Union[str, Sequence[str], None] = "b57648f88fc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("pinned", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("settings", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "settings")
    op.drop_column("chats", "pinned")
    # ### end Alembic commands ###
