"""reorganaize id field in models

Revision ID: 16c3a2ff1f7e
Revises: bd45129b23a3
Create Date: 2026-02-05 03:03:52.591731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "16c3a2ff1f7e"
down_revision: Union[str, Sequence[str], None] = "bd45129b23a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
