"""add refresh token support

Revision ID: 99199c0a212d
Revises: 56b7545a27dd
Create Date: 2026-02-07 23:47:02.599805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "99199c0a212d"
down_revision: Union[str, Sequence[str], None] = "56b7545a27dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("refresh_token", sa.String(length=512), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("refresh_token_expires_at", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "refresh_token_expires_at")
    op.drop_column("users", "refresh_token")
    # ### end Alembic commands ###
