"""fix api key in user model

Revision ID: 656a09648f8f
Revises: 930ba8d7b90f
Create Date: 2026-02-08 06:10:57.898063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "656a09648f8f"
down_revision: Union[str, Sequence[str], None] = "930ba8d7b90f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("api_key", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("api_key", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
