"""fix chat reletionship

Revision ID: 930ba8d7b90f
Revises: 99199c0a212d
Create Date: 2026-02-08 05:39:14.031622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "930ba8d7b90f"
down_revision: Union[str, Sequence[str], None] = "99199c0a212d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
